### ISSUE TITLE
[Feature Request] Option to hide version dropdown menu and link directly to specific tag site

### ISSUE THREAD

**Issue by dgkf** [docat-org/docat#123]
Sometimes it's nice to link users to documentation without the option to bounce between versions. Especially if the production version of a product isn't on the latest release, users might see the version option and want to jump to the latest release assuming it is the deployed version but see docs that are out-of-sync with their use.

In this scenario, it would be helpful to be able to link to a specific version without the option to switch. 

For example, perhaps `mydocat.com/project/tag` links to the docs with the version switching ui, but `mydocat.com/project/tag?hideui=1` just displays the raw documentation page, or the page with docat header, but no version toggle.

**Comment by reglim** [comment]
@dgkf 
Ok, I made a parameter `hideui` that just hides the `home` and `version` controls. What I thought was maybe you'd like to have a button in said controls to switch to the hidden version of the page, so you don't have to change that in the URL. 

@fliiiix , @randombenj and @dgkf 

Could you tell me what you think of that idea?

**Comment by reglim** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/79848181/193750848-33b1d72e-26ce-495f-b08d-7305a1a70bf0.png)
