### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by m-masterton** [docat-org/docat#133]
Whenever I try to upload a file using the commands shown in the docatl help menu, I get the following error.
```docatl --host http://localhost push ~/docs/gravity.zip myproject 1.0.0 -t latest```
I recive the error, unable to upload documentation: (status code: 404)

**Comment by timofurrer** [comment]
Is your docat server really running on `localhost` port `80` ? Or is something else running there?

**Comment by fliiiix** [comment]
closed because there are no additional information - feel free to reopen with more info
