### ISSUE TITLE
blink issue

### ISSUE THREAD

**Issue by Ninebell** [docat-org/docat#271]
Hello,
I'm trying to using this framework for making my documents. But when I change my page, there's some blink.
Maybe it's because of the force update. 
Is there any some solution for fixing it? or Is that in your plan?

https://user-images.githubusercontent.com/41539605/191137504-0e1aea0b-5090-4ac0-89ff-87d6b3899929.mov

**Comment by fliiiix** [comment]
isn't that just because there is a different html page loaded?

**Comment by Ninebell** [comment]
@fliiiix 
I made it by sphinx.  And other documents site like networkx document page, It doesn't blink.
And when I check it in local not hosting, It didn't happen.

**Comment by randombenj** [comment]
As with 1.0.0 we completely reimplemented the frontend. Is this still an issue? @Ninebell

**Comment by aragilar** [comment]
I think this is still an issue. If you create a simple sphinx site, and serve it via docat and `python3 -m http.server`, you'll see a blink transition with docat but no blink with `python3 -m http.server` (tested with Firefox 114 and Chromium 114 on Linux). I'm guessing this is related to how the page is being served out (I've not looked into how the overlays are added).

**Comment by aragilar** [comment]
Yep, I think it's related to the iframe setup, if I go to http://localhost:8000/doc/project/version/ then the blinking doesn't happen.

**Comment by reglim** [comment]
I think this is now fixed with #587 . Feel free to reopen if it's still an issue.
