### ISSUE TITLE
UI is broken with the new logos

### ISSUE THREAD

**Issue by fliiiix** [docat-org/docat#277]
![image](https://user-images.githubusercontent.com/1682954/191982634-38e0a2d3-eeba-4488-9cc7-ac23771db97c.png)

we should fix that first before I do a new release
maybe @reglim can do that on monday?

**Comment by reglim** [comment]
@fliiiix I can do that. I don't know how the UI should look, though... Should the logo just be in line with the Project name?

**Comment by randombenj** [comment]
@reglim exactly

**Comment by reglim** [comment]
@randombenj 
@fliiiix 

Does this look good, or should I change it? This was just the the result of putting it all on one line:

![image](https://user-images.githubusercontent.com/79848181/192305416-19e0bff0-73ca-45e9-8a0a-018e6c000d84.png)

(Sorry for the Logos btw, I didn't have any lying around except these :) )

**Comment by randombenj** [comment]
@reglim Perfect!
