### ISSUE TITLE
[Feature Request] Alternative database technology

### ISSUE THREAD

**Issue by aqemia-aalixe** [docat-org/docat#329]
Hey, 

First of all, I love docat project. It does what it needs to do and is easy to use. 

I wanted to use this project for documentation versioning at work, but the fact that the database is local with tinydb is a no-go since it would be used on an auto-scaling group with no shared mounting point.

I wonder if you would be interested in a feature to let the user use another database like postresql as an alternative to tinydb so that we could use a remote db. 

Let me know if you are interested, if you want more precision.
If it is ok, I can produce the code for it after we discussed about the implementation 

Sincerely :)

**Comment by randombenj** [comment]
> First of all, I love docat project. It does what it needs to do and is easy to use.

Glad to hear that you like the project :) 
Simplicity is one of our main design decisions, hence the usage of tinydb.

What exactly do you want to scale? If you do scaling, you anyway need to store the docs on a shared file system,
then you can also store the database there, right?
Our goal is to keep docat as simple as possible, setting up a postgresql would make the setup much more complicated than 
it is right now.
