### ISSUE TITLE
Handle 'latest' tag not as a version rather combine it like 1.2.3 (latest)'

### ISSUE THREAD

**Issue by kraeki** [docat-org/docat#40]
Hi guys
I would like to see the 'latest' tag behind the actual version. 
Right now it looks like latest is a custom version. 

![image](https://user-images.githubusercontent.com/1683039/73838893-02666700-4815-11ea-9bae-a35c664b4ed7.png)

**Comment by BrunnerLivio** [comment]
The tag shall be configureable in my opinion. For example, I want to tag certain versions as review, so I'd use the `review` tag and it should display it as such in the docs.
