### ISSUE TITLE
Deep links are broken

### ISSUE THREAD

**Issue by fliiiix** [docat-org/docat#479]
On main deep links with `#` are broken:

 https://docs.company.com/#/project/6.7.0/#_carriers

**Comment by randombenj** [comment]
Back in vue times, we used an eventlistener for this: https://github.com/docat-org/docat/blob/0.3.0/web/src/pages/Docs.vue#L118

@reglim maybe this went missing while implementing the new frontend?

**Comment by reglim** [comment]
Yeah, probably, but I'm not sure how we can fix that...
