### ISSUE TITLE
how to show "you not reading the most recent version of this documentation" if I read old doc

### ISSUE THREAD

**Issue by larrycai** [docat-org/docat#480]
this is common pattern for doc system, to show hints that you are reading the old doc

Like https://sphinx-rtd-theme.readthedocs.io/en/1.1.1/ , then I got notes

````
You are not reading the most recent version of this documentation. [1.2.0](https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/) is the latest version available.
````

Do we possible to have this feature in header/footer already

**Comment by randombenj** [comment]
Great idea! I don't think that this should be too hard to implement, first we need to fix some bugs in the upcoming release.

**Comment by randombenj** [comment]
Yes!

**Comment by larrycai** [comment]
I tested, it works as expected (no link to latest is ok for me)

BTW: in the help, there is no version for docat, little bit tricky to know which version is used.
