### ISSUE TITLE
Nginx issue

### ISSUE THREAD

**Issue by sequoiap** [docat-org/docat#509]
I'm running the commands as given in the readme, and I'm able to upload (using curl) a zipped folder containing the html output of Sphinx where ``index.html`` is at the top level, and I get a "success" response. (I'm building my docs using JupyterBook.) The project than shows up in the docat landing page, but navigating to the project docs itself returns an Nginx 404 error. I can upload a single ``index.html`` file, and that displays. But the zipped directory is not working.

**Comment by fliiiix** [comment]
Can you share the zip file to have a look at it?

**Comment by sequoiap** [comment]
It was my fault. I finally figured out that I shouldn't just zip up the ``html/`` folder from ``_build/`` (I'm using Sphinx), but rather the *contents* of the ``html/`` folder. So, my ``index.html`` was nested one layer too deep. Maybe we can add a short note to the README as a "common mistake" to help future users.

**Comment by randombenj** [comment]
Maybe issuing a warning in the api response when no `/index.html` file is found in the zip file would be nice.
I think we can keep the issue open to address something like this what do you think @fliiiix ?
