### ISSUE TITLE
Sort versions (newest version first)

### ISSUE THREAD

**Issue by randombenj** [docat-org/docat#51]
Versions are sorted in the wrong order. This should be changed

**Comment by randombenj** [comment]
@galaplexus I think it kind of is, but only as 'string like', I don't know if this is is a good enough result:

![image](https://user-images.githubusercontent.com/5184499/152813706-3c5df36f-e828-4641-9b69-92412576fe2a.png)

**Comment by galaplexus** [comment]
You are right. More problematic. Since it's string comparison, version 1.12.0 will appear as earlier than 1.1.0
