### ISSUE TITLE
Question: Uploading files seems to override the index.html

### ISSUE THREAD

**Issue by robinmatz** [docat-org/docat#560]
Hello, I just found this project and seem to get stuck in the setup.

I am running the project locally with docker like stated in the documentation
```
mkdir -p docat-run/doc
docker run \
  --detach \
  --volume $PWD/docat-run:/var/docat/ \
  --publish 8000:80 \
  ghcr.io/docat-org/docat
```

I uploaded a zipped index.html file

```
curl -X POST -F "file=@docs.zip" http://localhost:8000/api/new-project/1.0.0
{"message":"File successfully uploaded"}
```
and on the UI, I can see the new project and can navigate to its index.html. 

However, when I upload another file

```
curl --header "Docat-Api-Key: c0eefad74d00d4cc3eb6287dd8345f5d" -X POST -F "file=@Dockerfile" http://localhost:8000/api/new-project/1.0.0/
{"message":"File successfully uploaded"}
```

and I navigate to the new-project, then I get a 404 from nginx

![image](https://github.com/docat-org/docat/assets/76647407/ab2077b2-9029-41cb-92fd-44180001d0a0)

**Comment by fliiiix** [comment]
The workflow is you gather all files for your documentation version put them in a zip and upload them at once.

Not sure what you are trying to do.

**Comment by robinmatz** [comment]
After uploading the documentation, I want to upload additional files, because that's what I thought was the process. Create a project with documention and then start uploading files

**Comment by fliiiix** [comment]
yes you need to upload all files at once, and project and version getting automatically created if they don't exist

there is no adding files, just replacing everything
