### ISSUE TITLE
Allow setting path to entry point

### ISSUE THREAD

**Issue by matze** [docat-org/docat#581]
Right now, the doc link only works if an `index.html` is present in the root of the uploaded zip file otherwise there will be a 404. However, there a few documentation generation systems that do not have an `index.html` in the root, for example `cargo doc` generates one per each crate including the dependency. It would be nice to specify the path to an entry point while uploading, for example in an HTTP header.

**Comment by fliiiix** [comment]
Thanks for reaching out and using docat :tada: 

I took a look at the config and it seems there is a small bug.
https://github.com/docat-org/docat/pull/582

And there you have the option to override it to use a different index file.
But `index.html` is the de-facto standard for that usecase and we try to keep the options and configuration as limited as possible. For that reason i don't think we will ever add a option to configure a different entry point per project version. 

You can use direct links even if you don't have a `index.html` like this

> http://localhost:8000/#/<project name>/<version>/foo.html

And for cargo specifically there are a few issues you can track where they want to add support for something like this
https://github.com/rust-lang/cargo/issues/739

and in the meantime i would create a small shell script adding a `index.html` to your zip before uploading.
