### ISSUE TITLE
Allow to hide versions in dropdown

### ISSUE THREAD

**Issue by BrunnerLivio** [docat-org/docat#62]
I would like to hide versions in the headers dropdown menu via the docat API

Use cases:

- Versions which only get deployed for internal purposes (e.g. for reviews)
- Keeping version links live, but making it accessible via the user interface

**Comment by randombenj** [comment]
This is a good idea, you could then deploy 'hidden' alpha versions for example, I think for this we need to rework the api a bit @fliiiix
