### ISSUE TITLE
Query available versions of a project

### ISSUE THREAD

**Issue by palto42** [docat-org/docat#740]
Is it possible to query a list of available versions for a specified project?

I would like to write some clean-up script which deletes all but the X newest versions.

**Comment by randombenj** [comment]
Yes, querying the [`/api/projects/{NAME}`](https://github.com/docat-org/docat/blob/main/docat/docat/app.py#L79) api should yield all versions of the project.

**Comment by palto42** [comment]
@randombenj  Thanks a lot, works :+1:
