### ISSUE TITLE
does it support `*.tar` file instead of `*.zip` for upload

### ISSUE THREAD

**Issue by larrycai** [docat-org/docat#916]
In the doc, it states `*.zip`.

Does it support `*.tar` or `*.tar.gz` file instead of `*.zip` for upload

check the code https://github.com/docat-org/docat/blob/main/docat/docat/utils.py#L66 , it only supports `*.zip`

The reason for this issue: I package my documents inside sphinx container, which doesn't have `zip` command.

**Comment by fliiiix** [comment]
Yes only *.zip is supported as it is the only format supported by windows and linux and mac os without hassle. 

Is it possible to just add the go binary for https://github.com/docat-org/docatl to your container? Which seems to me the simplest solution to get a zip and http client inside this container.

**Comment by larrycai** [comment]
This is a good solution, I like it. 

// I can use container to zip the file, docatl is a good place!
